server:
  port: 8090

spring:
  application:
    name: sql-generator
  main:
    banner-mode: off

  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size:
        5MB
      max-request-size:
        5MB
